Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
popularidades_df <- data.frame(
    Presidente = character(),
    Data = as.Date(character()),
    FimData = as.Date(character()),
    OtimoBom = integer(),
    Regular = integer(),
    RuimPessimo = integer(),
    NaoSabe = integer())

for(presidente in presidentes) {
    popularidade <- read.table(paste("./dados/popularidade_",
                                     presidente,
                                     ".txt",
                                     sep = ""),
                                header = TRUE)
    popularidade$Data <- as.Date(popularidade$Data, "%d.%m.%Y")
    popularidade$Presidente <- rep(presidente, nrow(popularidade))
    popularidades_df <- rbind(popularidades_df, popularidade)
}

popularidades_df$FimData <- lag(popularidades_df$Data)
popularidades_df$Presidente <- factor(popularidades_df$Presidente,
                                      levels = presidentes)

head(popularidades_df)
tail(popularidades_df)
------------------

Error in file(file, "rt"): cannot open the connection
Traceback:

1. read.table(paste("./dados/popularidade_", presidente, ".txt", 
 .     sep = ""), header = TRUE)
2. file(file, "rt")
ERROR: Error in file(file, "rt"): cannot open the connection


